# parameters used by the different modules
perception:
  tag_detector:
    aruco_dict:
      "4x4_1000"
    aruco_params:
      "standard"
    plot:
      True

  semantic_segmentation:
    contour_min_length:
      30
    image_shape_resized:
      [1024, 576]
    weight_path:
      "BiSeNet/res/tuve_0505/tuve_0505_final.pth"

  overlapping_area_fusion:
    tag_history_length: 1.0
    plot: False

# general parameters
robots:
  geometry:
    width: 0.56
    length: 0.72
    height: 0.74

tags:
  robots:
    ids: [10, 12, 16]
    size: 0.098

