<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  
  <!-- Main Body-base -->
  <xacro:property name="base_x_size" value="0.72" />
  <xacro:property name="base_y_size" value="0.55" />
  <xacro:property name="base_z_size" value="0.23" />
  <xacro:property name="base_mass" value="15" /> <!-- in kg-->
  <xacro:property name="base_z_origin_to_wheel_origin" value="-0.07" />

   <!-- Wheels -->

  <xacro:property name="wheel_radius" value="0.125" /> 
  <xacro:property name="wheel_height" value="0.032" />
  <xacro:property name="wheel_mass" value="0.3" /> <!-- in kg-->

  <xacro:property name="swivel_wheel_radius" value="0.05" /> 
  <xacro:property name="swivel_wheel_height" value="0.05" />
  <xacro:property name="swivel_wheel_mass" value="0.5" /> <!-- in kg-->

  <!-- Table -->

  <xacro:property name="pillar_radius" value="0.025" /> 
  <xacro:property name="front_pillar_length" value="0.53" /> 
  <xacro:property name="back_pillar_length" value="0.38" />
  <xacro:property name="pillar_mass" value="0.1" />

  <xacro:property name="table_length" value="0.72" />
  <xacro:property name="table_width" value="0.56" />
  <xacro:property name="table_height" value="0.04" />
  <xacro:property name="table_pillar_off_x" value="0.15" />
  <xacro:property name="table_pillar_off_y" value="0.095" />
  <xacro:property name="table_mass" value="1" /> <!-- in kg-->

  <xacro:property name="pillar_off_x" value="${pillar_radius+table_pillar_off_x-(table_length/2.0)}" />
  <xacro:property name="pillar_off_y" value="${pillar_radius+table_pillar_off_y-(table_width/2.0)}" />
  <xacro:property name="pillar_off_z_back" value="${back_pillar_length+(table_height/2.0)}" />
  <xacro:property name="pillar_off_z_front" value="${front_pillar_length+(table_height/2.0)}" />
  


  <!-- Inertias -->

  <!--Inertial macros for the box and cylinder. Units are kg*m^2-->
  <xacro:macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
              iyy="${m*(x*x+z*z)/12}" iyz = "0"
              izz="${m*(x*x+z*z)/12}" />
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </xacro:macro>



</robot>
