# TODO: move the controller params to the atr_controller package
atr_controller_1:
  ros__parameters:
    atr_id : 1
    state_topic_name: "atr_driver_state"
    state_publish_period_us: 10000
    command_topic_name: "joint_command"
    teleop_topic_name: "teleop"
    enable_topic_stats: False
    topic_stats_topic_name: "controller_stats"
    topic_stats_publish_period_ms: 1000
    deadline_duration_ms: 0
    controller:
      #Kp_x,Kp_y,Kp_o, Kd_x, Kd_y,Kd_o [1.3, 1.3, 1.0, 0.00030, 0.0003, 0.00010] 
      feedback_matrix: [10.3, 10.3, 3.1, 0.6, 0.6, 0.350]
      teleop_factors: [1.0, 1.0, 1.0]

atr_driver_1:
  ros__parameters:
    atr_id: 1
    frame_id: "world"
    joint_state_topic_name: "joint_states"
    state_topic_name: "atr_driver_state"
    atr_state_topic_name: "atr_state"
    command_topic_name: "joint_command"
    disturbance_topic_name: "disturbance"
    cart_base_joint_name: "cart_base_joint"
    pole_joint_name: "pole_joint"
    state_publish_period_us: 10000
    enable_topic_stats: False
    topic_stats_topic_name: "driver_stats"
    topic_stats_publish_period_ms: 1000
    deadline_duration_ms: 0
    driver:
      wheel_length: 0.48
      wheel_radius: 0.125
      damping_coefficient: 20.0
      gravity: -9.8
      max_wheel_speed: 1000.0
      noise_level: 0.0
      initial_state: [0.66, 5.09, 0.0]
      # initial_state: [0.0, 0.0, 0.0]
    factory_state_topic_name: ""

atr_controller_2:
  ros__parameters:
    atr_id: 2
    state_topic_name: "atr_driver_state"
    state_publish_period_us: 10000
    command_topic_name: "joint_command"
    teleop_topic_name: "teleop"
    enable_topic_stats: False
    topic_stats_topic_name: "controller_stats"
    topic_stats_publish_period_ms: 1000
    deadline_duration_ms: 0
    controller:
      #Kp_x,Kp_y,Kp_o, Kd_x, Kd_y,Kd_o [1.3, 1.1, 0.0030, 0.0010]
      feedback_matrix: [10.3, 10.7, 10.1, 0.6, 0.6, 0.350]
      teleop_factors: [1.0, 1.0, 1.0]

atr_driver_2:
  ros__parameters:
    atr_id: 2
    frame_id: "world"
    joint_state_topic_name: "joint_states"
    state_topic_name: "atr_driver_state"
    atr_state_topic_name: "atr_state"
    command_topic_name: "joint_command"
    disturbance_topic_name: "disturbance"
    cart_base_joint_name: "cart_base_joint"
    pole_joint_name: "pole_joint"
    state_publish_period_us: 10000
    enable_topic_stats: False
    topic_stats_topic_name: "driver_stats"
    topic_stats_publish_period_ms: 1000
    deadline_duration_ms: 0
    driver:
      wheel_length: 0.48
      wheel_radius: 0.125
      damping_coefficient: 20.0
      gravity: -9.8
      max_wheel_speed: 1000.0
      noise_level: 0.0
      initial_state: [3.0, 3.0, 0.0]
    factory_state_topic_name: ""

atr_controller_3:
  ros__parameters:
    atr_id: 3
    state_topic_name: "atr_driver_state"
    state_publish_period_us: 10000
    command_topic_name: "joint_command"
    teleop_topic_name: "teleop"
    enable_topic_stats: False
    topic_stats_topic_name: "controller_stats"
    topic_stats_publish_period_ms: 1000
    deadline_duration_ms: 0
    controller:
      #Kp_x,Kp_y,Kp_o, Kd_x, Kd_y,Kd_o [1.3, 1.1, 0.0030, 0.0010]
      feedback_matrix: [10.3, 10.7, 10.1, 0.6, 0.6, 0.350]
      teleop_factors: [1.0, 1.0, 1.0]
